KidsCryptoClient/Models/CryptoFact.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace KidsCryptoClient.Models
{
    public class CryptoFact
    {
       
            public int IdCryptoFact { get; set; }

            public int? CryptoFactId { get; set; }

            public string Fact { get; set; } = null!;

           
        
    }
}

KidsCryptoClient/Models/CryptoNews.cs
namespace KidsCryptoClient.Models
{
    using System;
    using Newtonsoft.Json;

    public  class CryptoNews
    {
        [JsonProperty("title")]
        public string? Title { get; set; }

        [JsonProperty("url")]
        public Uri? Url { get; set; }

        [JsonProperty("source")]
        public string? Source { get; set; }
    }
}

KidsCryptoClient/Models/ErrorViewModel.cs
namespace KidsCryptoClient.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

KidsCryptoClient/Controllers/HomeController.cs
using KidsCryptoClient.Models;
using KidsCryptoClient.Services;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Serilog;
using System.Diagnostics;

namespace KidsCryptoClient.Controllers
{
    public class HomeController : Controller
    {
        

        private readonly ILogger<HomeController> _logger;

        public HomeController(ILoggerFactory loggerFactory)
        {
            Log.Logger = new LoggerConfiguration()
            .WriteTo.File("log.txt", rollingInterval: RollingInterval.Day)
            .CreateLogger();

            _logger = loggerFactory.CreateLogger<HomeController>(); //dpi
        }





        public async Task<IActionResult> IndexAsync()
        {
            IEnumerable<CryptoNews> cryptoNews = new List<CryptoNews>();    

            try
            {
                cryptoNews = await NewsService.GetNewsAsync();
            }
            catch (HttpRequestException ex)
            {
                // Serilog
                Log.Error(ex, "An error occurred while sending the HTTP request to Crypto News.");
            }
            catch (JsonException ex)
            {
               
                Log.Error(ex, "An error occurred while deserializing the JSON response.");
            }




            return View("Index", cryptoNews??Enumerable.Empty<CryptoNews>());
        }

       


        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        ~HomeController()
        {
            Log.CloseAndFlush();
        }
    }
}

KidsCryptoClient/Controllers/LearnController.cs
using KidscryptoLib.Models;
using KidsCryptoClient.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using Serilog;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;

namespace KidsCryptoClient.Controllers
{
    public class LearnController : Controller
    {
        private readonly ILogger<LearnController> _logger;
        private IEnumerable<KidsCryptoClient.Models.CryptoFact> facts;

        public LearnController(ILoggerFactory loggerFactory)
        {
            Log.Logger = new LoggerConfiguration()
              .WriteTo.File("log.txt", rollingInterval: RollingInterval.Day)
              .CreateLogger();

            _logger = loggerFactory.CreateLogger<LearnController>();//dpi

        }

        public async Task<IActionResult> Index()
        {
            facts  = await CryptoFactService.GetCryptoFacts();


            //try
            //{
            //    facts = await CryptoFactService.GetCryptoFacts();

            //}
            //catch (HttpRequestException ex)
            //{
            //    // Serilog
            //    Log.Error(ex, "An error occurred while sending the HTTP request to Crypto Facts API.");
            //}
            //catch (JsonException ex)
            //{

            //    Log.Error(ex, "An error occurred while deserializing the JSON response.");
            //}

            Models.CryptoFact[] cryptoFacts = facts.ToArray();

            return View("NewFact", cryptoFacts[1]);
        }

        public object NewFact(){

            Models.CryptoFact [] cryptoFacts = facts.ToArray();


        return View("NewFact", cryptoFacts[1]);
        }


        ~LearnController()
        {
            Log.CloseAndFlush();
        }
    }
}

KidsCryptoClient/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
@model IEnumerable<CryptoNews>

<h1>Crypto News</h1>

<div class="news-container">
    @foreach (var news in Model)
    {
        <div class="news-item">
            <h2>@news.Title</h2>
            <p>@news.Source</p>
            <a href="@news.Url">Read More</a>
        </div>
    }
</div>

@section Scripts {

    <script>
        $(document).ready(function () {
            $('.news-item').addClass('shadow p-3 mb-5 bg-white rounded');
        });
    </script>
}



@*
<div> News </div>
<div> Excange</div>
<div>Learn</div>
<div>Quizz</div>
*@

KidsCryptoClient/Views/Learn/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

KidsCryptoClient/Views/Learn/NewFact.cshtml
@model KidsCryptoClient.Models.CryptoFact

@{
    ViewData["Title"] = "View";
}

<h1>View</h1>

<div>
    <h4>CryptoFact</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdCryptoFact)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdCryptoFact)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CryptoFactId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CryptoFactId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Fact)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Fact)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

KidsCryptoClient/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - KidsCryptoClient</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/cutsom.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/KidsCryptoClient.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light" style="background-color: rgba(52,201,235,0.7);">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">
                    <img src="~/Assets/logo.PNG" alt="KidsCryptoLogo" width="100" height="100" class="d-inline-block align-text-top rounded-circle">
                    
                </a>
                <span class="fs-2 fw-bold text-center">KidsCrypto</span>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item">
                            <a class="nav-link fs-4 fw-bold" href="@Url.Action("Index", "Home")">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link fs-4 fw-bold" href="@Url.Action("Index", "Learn")">Learn</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link fs-4 fw-bold" href="#">Quizz</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link fs-4 fw-bold" href="#">Rate Us</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>


    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="footer bg-light">
        <div class="container text-center">
            <span class="text-muted">&copy; 2023 - KidsCryptoClient - Designed by Jelena Ndou</span>
            <span class="dollar-sign"></span>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>